### ISSUE TITLE
[Feature Request] Service Connection backed up by Certificate is not supported for running load test via Azure pipeline

### ISSUE THREAD

**Issue by agrawalamit31** [microsoft/azure-load-testing#37]
**Is your feature request related to a problem? Please describe.**
We are running load test via Azure pipeline where Service connection is using client secret. We observed Load Testing is not supported certificate in Service connection though certificate is recommended for security standpoint .

**Describe the solution you'd like**
Please provide support for Service Connection backed up by Certificate to run load test via Azure pipeline.

**Additional context**
We are getting below error if we use Service Connection backed up by Certificate.

`(node:1600) UnhandledPromiseRejectionWarning: Error: Endpoint auth data not present: cd80e187-3750-431f-8d01-f70e51cba41b

at Object.getEndpointAuthorizationParameter (/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/node_modules/azure-pipelines-task-lib/task.js:357:15)

at /home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/models/mappers.js:264:42

at Generator.next (<anonymous>)

at /home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/models/mappers.js:27:71

at new Promise (<anonymous>)

at __awaiter (/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/models/mappers.js:23:12)

at getAuthInputs (/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/models/mappers.js:260:12)

at Object.getInputParams (/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/models/mappers.js:215:5)

at /home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.87/index.js:48:17

at Generator.next (<anonymous>)

(node:1600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:1600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ninallam** [comment]
@agrawalamit31 thanks for the feedback. We will work on this to support service connections with certificates.

**Comment by agrawalamit31** [comment]
@[ninallam](https://github.com/ninallam) - Any update for this feature ?
